import type { Metadata, Viewport } from "next";
import { Inter, Sora, JetBrains_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { MotionProvider } from "@/components/motion-provider";
import { CookieConsent } from "@/components/layout/cookie-consent";
import { LocaleProvider } from "@/lib/i18n";
import { profile, brand } from "@/data/site";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
});

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
});

const SITE_URL = "https://hammadriaz.dev";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${profile.name} | ${profile.shortTitle}`,
    template: `%s | ${profile.name}`,
  },
  description: brand.heroSub,
  keywords: [
    "Hammad Ahmed Riaz",
    "Full Stack Engineer",
    "AI Application Developer",
    "React Developer Austria",
    "Next.js Developer",
    "Freelance Software Engineer Salzburg",
    "LLM Engineer",
    "RAG Developer",
    "Node.js Nest.js Developer",
    "DACH Software Engineer",
    "Hire Full Stack Developer",
  ],
  authors: [{ name: profile.name, url: profile.links.linkedin }],
  creator: profile.name,
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    title: `${profile.name} | ${profile.shortTitle}`,
    description: brand.heroSub,
    siteName: profile.name,
    // OG image auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: `${profile.name} | ${profile.shortTitle}`,
    description: brand.tagline,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
  alternates: { canonical: SITE_URL },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fbfbfd" },
    { media: "(prefers-color-scheme: dark)", color: "#07070b" },
  ],
  width: "device-width",
  initialScale: 1,
};

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Person",
      "@id": `${SITE_URL}/#person`,
      name: profile.name,
      jobTitle: "Full Stack Engineer & AI Application Developer",
      email: `mailto:${profile.email}`,
      telephone: profile.phone,
      url: SITE_URL,
      image: `${SITE_URL}/opengraph-image`,
      address: { "@type": "PostalAddress", addressLocality: "Salzburg", addressCountry: "AT" },
      sameAs: [profile.links.linkedin, profile.links.github],
      knowsAbout: ["React", "Next.js", "TypeScript", "Node.js", "Nest.js", "OpenAI", "RAG", "PostgreSQL", "AWS"],
      alumniOf: [
        { "@type": "CollegeOrUniversity", name: "FH Salzburg / University of Salzburg" },
        { "@type": "CollegeOrUniversity", name: "University of Gujrat" },
      ],
    },
    {
      "@type": "WebSite",
      "@id": `${SITE_URL}/#website`,
      url: SITE_URL,
      name: `${profile.name} | ${profile.shortTitle}`,
      description: brand.heroSub,
      inLanguage: ["en", "de"],
      publisher: { "@id": `${SITE_URL}/#person` },
    },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning className={`${inter.variable} ${sora.variable} ${jetbrains.variable}`}>
      <body className="antialiased">
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <MotionProvider>
          <LocaleProvider>
            <a
              href="#main"
              className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-lg focus:bg-brand-600 focus:px-4 focus:py-2 focus:text-white"
            >
              Skip to content
            </a>
            {children}
            <CookieConsent />
          </LocaleProvider>
          </MotionProvider>
        </ThemeProvider>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </body>
    </html>
  );
}
